import type { PromptSnippetDefinition } from "../types.js";

export const h3SnippetDefinitions: readonly PromptSnippetDefinition[] = [
  { id: "continuity-reference-lock", groupId: "continuity", text: "Use each supplied reference only for its assigned role. Preserve the identity, appearance, clothing ownership, spatial relationships, and composition anchors visibly established by the relevant reference while applying the requested changes." },
  { id: "continuity-body-gaze-lock", groupId: "continuity", text: "Keep each identified subject's body and gaze orientation continuous, changing them only where the requested action does so." },
  { id: "visual-live-action-human", groupId: "visual-realism", text: "Render the subject as a believable real person in live-action footage, with natural skin texture, subtle facial asymmetry, physically plausible anatomy, realistic hair and fabric response, and lighting consistent with the environment." },
  { id: "visual-anti-cg-plastic", groupId: "visual-realism", text: "Use live-action photographic material behavior: natural skin reflectance, fine hair, responsive fabric, varied surface detail, contact shadows, and restrained specular highlights." },
  { id: "visual-natural-materials", groupId: "visual-realism", text: "Preserve small real-world material variation through visible skin and fine hair, slight fabric irregularity, natural reflections, contact shadows, and uneven surface texture." },
  { id: "visual-natural-light", groupId: "visual-realism", text: "Use naturalistic lighting and exposure with believable shadow direction, gradual highlight roll-off, ambient bounce, and scene-consistent color response." },
  { id: "capture-smartphone-1x", groupId: "camera-capture", text: "Use an authentic older-smartphone 1x main-camera look with mild wide-angle perspective, ordinary exposure, subtle handheld drift, slight focus breathing, and restrained motion blur." },
  { id: "capture-documentary-handheld", groupId: "camera-capture", text: "Use observational documentary capture with practical light, modest handheld movement, responsive focus, imperfect framing, and restrained color processing." },
  { id: "motion-causal-onset", groupId: "motion-reaction", text: "Begin the main action with one visible preparation appropriate to that action, then carry its physical response forward continuously." },
  { id: "motion-vocal-anatomy", groupId: "motion-reaction", text: "The visible speaker uses natural lip and jaw motion with subtle breathing, then lets the mouth settle after the line." },
  { id: "camera-push-in", groupId: "camera-motion", text: "The camera pushes in with small amplitude at slow speed toward the subject." },
  { id: "camera-pull-out-reveal", groupId: "camera-motion", text: "The camera pulls out directly backward along the same optical axis with large amplitude at slow speed, progressively revealing the environment through realistic parallax." },
  { id: "camera-pedestal-up", groupId: "camera-motion", text: "The camera pedestals upward with small amplitude at slow speed and settles at the higher viewpoint." },
  { id: "camera-restrictions", groupId: "camera-motion", text: "Keep the viewpoint on the selected physical camera path, direction, target, and endpoint throughout the movement." },
  { id: "camera-continuous-take", groupId: "camera-motion", text: "One continuous unbroken take from the first frame to the last, with no editorial cut. Keep the scene, subjects, and spatial relationships continuous; express all reframing through smooth physical camera movement within [Shot 1]." },
  { id: "camera-pan-right", groupId: "camera-motion", text: "The camera pans right with small amplitude at slow speed, revealing the existing scene space to the subject's right." },
  { id: "camera-tracking", groupId: "camera-motion", text: "The camera uses a smooth tracking shot and follows the subject at a steady pace." },
  { id: "camera-static", groupId: "camera-motion", text: "The camera holds a static shot while the subject performs the action." },
  { id: "shot-close-up", groupId: "framing", text: "The shot cuts to a close-up that keeps the subject's face and key expression clearly visible." },
  { id: "shot-wide", groupId: "framing", text: "The camera pulls back along a continuous physical path to a wide view of the existing environment and its spatial relationships." },
  { id: "shot-framing-progression", groupId: "framing", text: "The camera moves continuously from a close view to a full-body environmental view along one readable physical path, preserving the subject's world scale." },
  { id: "motion-turn", groupId: "subject-motion", text: "The subject turns slowly toward the camera, moves naturally, and holds the final pose." },
  { id: "motion-breeze", groupId: "subject-motion", text: "A light breeze moves the subject's hair and clothing with subtle, physically consistent motion." },
  { id: "sound-ambience", groupId: "sound", text: "Use natural ambient sound, subtle movement sounds, and room tone grounded in the visible scene." },
  { id: "sound-synchronized-action", groupId: "sound", text: "Synchronize each diegetic sound with the visible action and environmental response that produces it." },
  { id: "sound-spatial-echo", groupId: "sound", text: "The direct sound becomes quieter as the camera moves away; delayed reflections arrive from the left and then the right, becoming progressively quieter, darker, and more diffuse." },
  { id: "sound-no-music", groupId: "sound", text: "Use N/A for non_diegetic_music." },
  { id: "dialogue-mandarin", groupId: "dialogue", text: "The speaker (S1) speaks Mandarin Chinese with a clear, natural voice and says exactly: <d>[Chinese] Write the exact original dialogue here.</d>" },
  { id: "dialogue-english", groupId: "dialogue", text: "The speaker (S1) uses a clear, natural English voice and says exactly: <d>[English] Write the exact spoken words here.</d>" },
  { id: "screen-text", groupId: "screen-text", text: "Any visible sign, subtitle, label, or neon text reads exactly \"Write the original text here\"; preserve its original punctuation without translation." }
];
