import { component, entry, guide } from "./catalog-helpers.js";
import type { CatalogModelEntry } from "../types.js";

export const postProcessModelEntries: CatalogModelEntry[] = [
  entry({ id: "seedvr2", family: "seedvr2", category: "upscale", adapterId: "seedvr2", order: 100, inputModes: ["video"], scan: { vram: "预计峰值 18–23 GB", components: [
    component("SeedVR2 主模型", "SEEDVR2/seedvr2_ema_3b 或 7b", /(?:^|\/)seedvr2\/.*seedvr2_ema_(?:3b|7b).*\.(safetensors|pt)$/i, guide("numz / SeedVR2_comfyUI", "https://huggingface.co/numz/SeedVR2_comfyUI/tree/main", "SEEDVR2", "seedvr2_ema_3b_fp8_e4m3fn.safetensors")),
    component("SeedVR2 VAE", "SEEDVR2/ema_vae*", /seedvr2\/.*ema_vae.*\.(safetensors|pt)$/i, guide("numz / SeedVR2_comfyUI", "https://huggingface.co/numz/SeedVR2_comfyUI/tree/main", "SEEDVR2", "ema_vae_fp16.safetensors"))
  ] } }, { name: "SeedVR2", badge: "推荐", description: "视频时间一致性优先，适合人物和真实画面。" }, { name: "SeedVR2", badge: "Recommended", description: "Prioritizes temporal consistency for people and realistic footage." }),
  entry({ id: "flashvsr", family: "flashvsr", category: "upscale", adapterId: "flashvsr", order: 90, inputModes: ["video"], scan: { vram: "预计峰值 14–19 GB", components: [
    component("FlashVSR 模型", "FlashVSR/FlashVSR1_1.safetensors", /flashvsr\/flashvsr1_1\.safetensors$/i, guide("1038lab / FlashVSR", "https://huggingface.co/1038lab/FlashVSR/tree/main", "FlashVSR", "FlashVSR1_1.safetensors")),
    component("Wan 2.1 VAE", "FlashVSR/Wan2.1_VAE.safetensors", /flashvsr\/wan2\.1_vae\.safetensors$/i, guide("1038lab / FlashVSR", "https://huggingface.co/1038lab/FlashVSR/tree/main", "FlashVSR", "Wan2.1_VAE.safetensors")),
    component("LQ Projection", "FlashVSR/LQ_proj_in.safetensors", /flashvsr\/lq_proj_in\.safetensors$/i, guide("1038lab / FlashVSR", "https://huggingface.co/1038lab/FlashVSR/tree/main", "FlashVSR", "LQ_proj_in.safetensors")),
    component("TCDecoder", "FlashVSR/TCDecoder.safetensors", /flashvsr\/tcdecoder\.safetensors$/i, guide("1038lab / FlashVSR", "https://huggingface.co/1038lab/FlashVSR/tree/main", "FlashVSR", "TCDecoder.safetensors")),
    component("Prompt Embedding", "FlashVSR/Prompt.safetensors", /flashvsr\/prompt\.safetensors$/i, guide("1038lab / FlashVSR", "https://huggingface.co/1038lab/FlashVSR/tree/main", "FlashVSR", "Prompt.safetensors"))
  ] } }, { name: "FlashVSR", badge: "平衡", description: "质量、速度和时间一致性的平衡选择。" }, { name: "FlashVSR", badge: "Balanced", description: "A balance of quality, speed, and temporal consistency." }),
  entry({ id: "realesrgan", family: "realesrgan", category: "upscale", adapterId: "realesrgan", order: 80, inputModes: ["video"], scan: { vram: "预计峰值 6–9 GB", components: [component("Real-ESRGAN x4 模型", "upscale_models/RealESRGAN*x4*", /upscale_models\/.*realesrgan.*x4.*\.(safetensors|pth|pt)$/i, guide("Real-ESRGAN 官方 Releases", "https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.5.0", "upscale_models", "RealESRGAN_x4plus.pth"))] } }, { name: "Real-ESRGAN x4plus", badge: "快速", description: "占用较低，适合快速检查和非人像内容。" }, { name: "Real-ESRGAN x4plus", badge: "Fast", description: "Low resource use for quick checks and non-portrait content." }),
  entry({ id: "rife", family: "rife", category: "interpolation", adapterId: "rife", order: 70, inputModes: ["video"], scan: { vram: "BF16 · 单帧批次 · 逐帧清缓存", components: [component("RIFE 4.7 插帧模型", "ComfyUI-Frame-Interpolation/ckpts/rife/rife47.pth", /frame_interpolation\/rife47\.pth$/i, guide("ComfyUI Frame Interpolation / RIFE", "https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/download/models/rife47.pth", "custom_nodes/ComfyUI-Frame-Interpolation/ckpts/rife", "rife47.pth"))] } }, { name: "RIFE Frame Interpolation", badge: "插帧", description: "将较少的生成帧插值到目标 FPS，降低视频大模型和 VAE 的总体压力。" }, { name: "RIFE Frame Interpolation", badge: "Interpolation", description: "Interpolates fewer generated frames to the target FPS, reducing total video-model and VAE load." })
];
