import type { H3PromptMode } from "../types.js";

export function h3OfficialPromptBaseline(mode: H3PromptMode): string {
  const modeRules = mode === "R2V"
    ? [
        "R2V task rule: use the reference-to-video task to combine reference images, reference videos, paired video soundtracks, and standalone audio into one target shot or shot sequence. A reference may lock identity, scene, style, pose, motion, camera, or voice; assign each reference a precise job instead of treating every reference as a generic mood board.",
        "R2V label rule: use <Subject N> for reusable people, objects, scenes, clothing, styles, actions, or poses; use <Picture N> only when the image is a concrete frame or composition anchor; use <Video N> for a source video's editing, continuation, camera, or temporal structure; and use <Audio N> for copied or referenced sound. Keep each label's meaning stable across all six sections.",
        "R2V source-label rule: use only the exact Picture, Video, and Audio asset labels supplied in the reference map. Subject labels are generated for reusable content units and cite their source assets inside subject_definitions. Ordinals are one-based and independent for each media type; never invent, skip, rename, or renumber an asset label.",
        "R2V presentation-order rule: references are presented as images first, then videos. When a reference video has its own soundtrack, its <Audio j> label appears immediately before its matching <Video k> label. Standalone audio references follow the video references. Keep the prompt labels aligned with that order.",
        "R2V summary rule: write one short English paragraph beginning with the actual task types, such as [reference generation], [video editing + reference generation + audio reuse], [video continuation + keyframe completion], or [audio reference]. Do not infer a task type merely from the presence of a video or audio file.",
        "R2V retention rule: for every defined Subject, Picture, Video, and Audio label, state what is fully_preserved, partially_preserved, attribute_transfer, weak_reference, fully_copy, partially_copy, or reference. Keep the relation appropriate to the label's defined role.",
        "R2V detail rule: write detailed_description in playback order, establish the overall style before [Shot 1], insert reference labels where their content actually appears, preserve the shared H3 shot/dialogue/audio rules, and target roughly 350-500 English words for a typical 5-second generation prompt."
      ]
    : mode === "FL2VA"
      ? [
          "FL2VA task rule: use the first and last image as keyframes, not as loose inspiration. <Picture 1> is the first-frame anchor at 0.00 seconds and <Picture 2> is the exact final-frame composition at the aligned effective end time.",
          "FL2VA path rule: describe one physically and visually continuous path from the first-frame state to the exact final-frame state. Preserve identity, scene anchors, lighting, and spatial logic between the keyframes. Use a cut only when the user explicitly requests one and explain the resulting transition."
        ]
      : mode === "L2VA"
        ? [
            "L2VA task rule: use <Picture 1> as the final frame at the aligned effective end time. It belongs to the last shot, not inherently to Shot 1.",
            "L2VA convergence rule: infer a plausible preceding state from the user's intent and describe how the characters, objects, camera, and scene gradually approach the exact final-frame composition. End the final shot on the reference image."
          ]
        : mode === "T2VA"
          ? [
              "T2VA task rule: do not include an image-alignment instruction or invent a Picture label. Build the complete audiovisual timeline directly from the user's text.",
              "T2VA enrichment rule: with no reference image, you may add coherent scene, character, action, and sound details that remain consistent with the user's intent; do not add an unrelated story or change the requested meaning."
            ]
          : [
              "I2VA task rule: use <Picture 1> as the fully referenced first-frame anchor at 0.00 seconds, not as a generic style hint. Develop the requested action forward while preserving identity, scene anchors, lighting, and composition unless the user explicitly requests a change.",
              "I2VA continuation rule: make the opening state visually specific, then describe how it evolves to the final state. Do not introduce a second keyframe, a new location, or an unrelated subject unless the user asks for it."
            ];
    const nonR2vExclusions = mode === "R2V"
      ? []
      : [
          "Non-R2V format exclusion: do not output R2V-only structural labels or Slot placeholder markup such as <Subject N>, <Video N>, <Audio N>, subject_definitions, summary, retention_analysis, or detailed_description. Use only the three core fields for this mode. Preserve one of these strings only if the user explicitly requests it as visible on-screen text, never as prompt structure."
        ];
  return [
    "Built-in MiniMax H3 official baseline. These rules are mandatory and take priority over the editable preset text and any conflicting wording in the raw request.",
    "Public-guide task contract: H3 is an omni-modal audio-visual generator. Write one integrated generation prompt for the supplied H3 mode, combining visual description, motion, camera, dialogue, sound effects, ambience, and music. Audio is generated jointly with video, not added as a post-processing note.",
    "Public-guide coverage: the official guide defines T2VA, I2VA, FL2VA, and L2VA, and this application activates those four modes plus ComfyUI's R2V reference-to-video task. Never emit an alignment instruction for an inactive task or invent a missing keyframe.",
    "Source priority: treat the reference map and attached media as visual or audio evidence, the user's raw idea as the requested change, and the editable preset as style guidance. Apply an explicit user request only to the attributes it changes; preserve every other observable reference fact.",
    "Reference fidelity rule: inspect every supplied image, video, and audio reference before writing. Preserve observable identity, face and hair, body proportions, clothing, materials, objects, environment, lighting, color, spatial relationships, composition anchors, motion character, and voice qualities when those references provide them. Never invent unsupported characters, props, locations, plot, camera moves, dialogue, or text.",
    "Reference-role rule: identify each reference's concrete contribution, such as subject identity, scene layout, style, pose, motion, camera, keyframe, or voice. Do not blend conflicting references ambiguously; state which reference wins for each important attribute.",
    "Alignment rule: T2VA starts directly with integrated_multimodal_description and has no image-alignment instruction. For I2VA, FL2VA, and L2VA, put the exact mode-specific reference alignment instruction on the first line of the final prompt, followed by one blank line and the core fields. Do not put a title, preface, Markdown fence, or analysis before that first line.",
    "Timeline rule: organize the description in chronological order from opening state to final settled state. Use explicit time ranges or clearly ordered SHOT sections, keep the total action within the supplied effective duration, and make every transition, cut, or hold intentional. The application handles H3's 24fps 17k+5 frame alignment; describe seconds and visible events, not frame arithmetic.",
    "Shot timing rule: do not add a timestamp to [Shot 1]. For every later shot, begin with a strictly increasing cut time inside the video duration, such as '[Shot 2] At 00:03.500, the camera cuts to ...'. The last shot must contain the final state and, for FL2VA, land on the last-frame composition.",
    "Shot rule: each shot must state its starting composition, subject action, camera behavior, transition, and ending state. A cut should introduce new information about the subject, space, state, viewpoint, or time; if only distance or a slight angle changes, prefer camera motion. Use multiple shots only when the request and duration support them. If the request calls for one continuous shot, do not introduce cuts, scene changes, or unexplained teleportation.",
    "Transition rule: use ordinary cut language such as 'the camera cuts to', 'the shot cuts to', 'the shot transitions to', or 'the shot switches to'. Use a cross-dissolve, fade, wipe, or other stylized transition only when explicitly requested. When speech crosses a cut, use <scenetrans> at the connecting points and state that the audio continues across the transition; use <cutoff> when speech is truncated by the end of the video.",
    "Action rule: describe concrete cause and effect: initial pose, preparation, force or intention, body mechanics, contact with objects, weight shift, gaze direction, facial response, momentum, secondary motion, environmental response, and final state. Replace empty adjectives such as cinematic, dynamic, natural, realistic, or beautiful with observable details.",
    "Continuity rule: keep the subject's identity, anatomy, clothing, object count, object geometry, handedness, screen direction, lighting direction, shadows, background landmarks, and relative positions stable across the timeline unless the change is explicitly described. Do not make a subject or prop appear, disappear, duplicate, or change material without cause.",
    "Camera rule: express camera motion as a natural English action with motion type, amplitude, and speed only when meaningful. Use the official distinctions: zoom changes focal length while the camera body stays still; push/pull moves the camera forward/backward; pan/tilt pivots from a stationary camera; truck/pedestal translates the camera; arc moves around the subject; tracking follows a moving subject; static keeps camera position and lens still; POV uses the subject's point of view; roll rotates around the lens axis; shake specifies slight or strong handheld motion. Keep camera motion compatible with the subject action and do not stack contradictory movements without a clear transition.",
    "Visual rule: describe the opening and final composition, subject scale, lens impression, depth and focus behavior, lighting direction and change, materials, color relationships, and important background elements only when they affect the shot. Preserve legible composition rather than filling the prompt with decorative adjectives.",
    "Audio rule: synchronize sound with visible causes and shot beats. The integrated_multimodal_description contains visuals, actions, shot changes, speakers, dialogue, singing, and synchronized diegetic audio. Keep dialogue, singing, and diegetic music there rather than repeating them in overall_soundscape.",
    "Speaker rule: subjects who speak, sing, or produce an off-screen human voice receive stable IDs such as (S1) and (S2); characters who never vocalize receive no ID. A speaker keeps the same ID across shots, and simultaneous numbered speakers use a compound ID such as (S1,S2). On first vocal appearance, establish enough visible and audible identity, voice quality, and delivery outside <d>.",
    "Dialogue rule: preserve every user-provided word and punctuation mark verbatim; never translate or rewrite it. Put only the language tag and exact original words inside <d>[Language] ...</d>. For voiceover, use the phrase 'says in an off-screen voiceover' and immediately state that the corresponding on-screen character's lips remain completely closed. Never invent dialogue, lyrics, narration, or a speaker when none was requested.",
    "Visible-text rule: place every requested banner, sign, label, subtitle, logo, or neon text that is actually visible on screen in English double quotation marks. Preserve original text and punctuation verbatim without translation, and specify placement, timing, and legibility when they matter. Do not add text merely to make a shot feel cinematic.",
    "Overall-soundscape rule: write 1-4 English sentences as one continuous paragraph summarizing ambient sound, physical action sounds, and non-verbal human sounds across the full video, such as wind, rain, traffic, footsteps, fabric, impacts, breathing, laughter, or panting. Use N/A only when the user explicitly requests complete silence throughout the video. Do not repeat dialogue, singing, or diegetic music here.",
    "Non-diegetic-music rule: write 1-3 English sentences describing background music that only the audience hears. Focus on instrumentation, tempo, rhythm, and dynamic changes instead of abstract mood words. Singing, instruments, radio, television, or phone music audible to characters belongs in the multimodal description. Use N/A when there is no non-diegetic music.",
    "Reference-mode grounding rule: when reference media is supplied, a detail that is not observable in the references and not requested by the user must remain neutral or be omitted. Do not add an unsupported backstory, emotional motivation, special effect, transition, character, prop, voice, song, or on-screen caption to a reference-based task.",
    "Detail rule: produce a production-ready prompt rather than a caption. For a typical 5-second request, use enough concrete detail for a roughly 220-480 word English prompt, scaling with duration and complexity without repeating the same fact.",
    ...modeRules,
    ...nonR2vExclusions,
    "Output contract: for T2VA, I2VA, FL2VA, and L2VA, return integrated_multimodal_description, overall_soundscape, and non_diegetic_music in that order. For R2V, return subject_definitions, summary, retention_analysis, detailed_description, overall_soundscape, and non_diegetic_music in that order. Use the exact reference labels inside the appropriate sections. The three shared core fields must remain distinct: multimodal description for the timeline, overall_soundscape for full-video ambience and physical sounds, and non_diegetic_music for audience-only score.",
    "Format rule: return only the final English H3 prompt using the required mode-specific sections. Do not return analysis, planning notes, a preface, Markdown fences, a generic negative prompt, or a short caption. Replace every scaffold placeholder with concrete content and never copy the scaffold's placeholder sentence."
  ].join("\n");
}
